2024-09-17T21:24:59.286536651-05:00   2024-09-18 02:24:59 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:openmetrics | Error running check: [{"message": "There was an error scraping endpoint http://172.20.255.233:7801/metrics: 404 Client Error: Not Found for url: http://172.20.255.233:7801/metrics", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 1122, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/v2/base.py\", line 67, in check\n    raise_from(type(e)(\"There was an error scraping endpoint {}: {}\".format(endpoint, e)), None)\n  File \"<string>\", line 3, in raise_from\nrequests.exceptions.HTTPError: There was an error scraping endpoint http://172.20.255.233:7801/metrics: 404 Client Error: Not Found for url: http://172.20.255.233:7801/metrics\n"}]